version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geodata-loader
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
      # Add any other necessary volume mounts here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
